#!/usr/bin/env python

import pathlib

Import("env")
module_env = env.Clone()

module_path = pathlib.Path(Dir(".").abspath)

env.Append(LIBPATH=[module_path / "thirdparty/sentry-native/install/lib"])
env.Append(LINKFLAGS=[
    "sentry.lib",
    "crashpad_client.lib",
    "crashpad_compat.lib",
    "crashpad_getopt.lib",
    "crashpad_handler_lib.lib",
    "crashpad_minidump.lib",
    "crashpad_snapshot.lib",
    "crashpad_tools.lib",
    "crashpad_util.lib",
    "crashpad_zlib.lib",
    "mini_chromium.lib",
    "winhttp.lib",
    "version.lib",
    "dbghelp.lib"
])
#env.Append(LIBS=["version", "winhttp", "dbghelp",])
env.Append(CPPPATH=["thirdparty/sentry-native/install/include"])

# Godot source files
module_env.add_source_files(module_env.modules_sources, "*.cpp")